### ISSUE TITLE
looking up https traffic with mitmproxy not working on android

### ISSUE THREAD

**Issue by gzawahra** [edenhaus/ha-prosenic#1]
hello, and thanks a lot for all your work, i ran into an issue trying to extract the necessary info on android i managed to get mitm running on windows (very simple) and intercept other http and https requests but proscenicHome app didn't want to connect i learned that this is because the mitm certificate was installed as a user certificate, moving it to system certificates means that you have to have a rooted android device, since this was my case i actually didn't need mitmproxy and just downloaded httpCanary, installed its certificate and moved it to the system certs, if you have root this is done by the app automatically, and only then was i able to view the request and extract the info, i know this is not really a problem on your part but i was hoping other people would see this and understand what's happening. oh and by the way could you maybe add and example for a lovelace card in the readme ? it would be much easier because i'm still trying to guess how to add this... thanks again !

**Comment by gzawahra** [comment]
oh and this is stupid but i noticed a small mistake in the entities card where it says "mob equipped
 true" i suppose you mean mop ? i don't if this is from your module or hassio in general.. thanks

**Comment by edenhaus** [comment]
thanks for your feedback. The typo is already fixed.
I have only iOS devices and therefore I could only test the code on that side. I have added a small sentence about rooted android devices, but I will keep it small. The most user don't ave a rooted one.

I used until know the standard vacuum card. It is the suggested one, if you try to add the vacuum robot to the UI.

Which model do you have? Also a 820T?

**Comment by gzawahra** [comment]
Hello! Thanks for the quick reply, yeah I know it's pretty rare to have a rooted phone but if you don't have an apple device that's the only way I can think of since I don't think they have a website version of the app,i have an 830t and I think that everything works great. I think you can add it to compatible vacuums, the only thing that's having trouble is the mop detection which is always true even if nothing is plugged in the back neither the vacuum bay nor the mop bay, is there a way to control the vacuum like the remote? With the arrows to go in the four directions manually? Are there anymore functions supported other than in this photo? Thanks! 
![Screenshot_20200310-224532_Home_Assistant](https://user-images.githubusercontent.com/33893670/76362404-49b6aa80-6321-11ea-9e8d-4d3d973e5562.png)

**Comment by edenhaus** [comment]
I also found out that the mob equipped is always true and I will fixed it probably tomorrow.
At the moment there is no possibility to control manually. One part of the code is already implemented, but I have still to register the service for manual control. The next question is, if it exists a UI card for manual control.... In my opinion the manual control is "useless". If I need to control the robot manually, it is a lot faster to use a normal "old" vacuum.

To come to the end. At the moment only the function from the above screenshot will work. Also mopping will work, if the mop is really equipped. I don't know if you have already saw it, but you can set in your configuration `remember_fan_speed: true`, which sets the old fan speed, when you start a new cleaning task. My robot runs always with the level strong.

**Comment by edenhaus** [comment]
@gibranZawahra Can I close this issue?
Short notice:
As reaction to the coronavirus, Italy was completely locked down and therefore I can't go to my student flat and work on the prosenic integration.

**Comment by gzawahra** [comment]
Hello @edenhaus, so sorry for the late reply, hope you and your family are all doing well during these times. Yes of course thanks a lot for fixing it so quickly I typed my reply a while ago but forgot to hit send lol. Thanks again for the great work and have a nice day!
