### ISSUE TITLE
Can't find Local_Key

### ISSUE THREAD

**Issue by terslowe** [edenhaus/ha-prosenic#2]
As first thank you so much for this intergration.

I have an issue to find the local_key via Mitmproxy. I can well find the device_id but not the local_key.

Is it possible to configure it in HASSio without the local_Key?

I am using Proscenic 790T

**Comment by edenhaus** [comment]
I don't have the 790T and therefore I can't give you 100% correct answer.
But I think, you need the local_key. On the 820 the local_key I used to encrypt the messages before sending to the robot. If you send unencrypted messages to the robot (at least for the 820T) then the will be rejected. 

Normally you can find the local_key in the json repsonse, where also the device_id is. Please logout on the app disinstall it and then start again. The local_key should be in one response. You probably need to check each response (the app send a couple of requests during login and fetching the devices)

Let me know, if you was able to get the local_key or if I can help you somehow

**Comment by terslowe** [comment]
Thank you for your answer and also that you want to help me. I did what you say log out log in deleted Robot from proscenic account and added again but no Local_Key. I have just added screenshots from that. 

- Is it possible to look for alternetive on Mitmproxy? Maybe that don't send the local key.
- Can i try wihthout the local_key on HASSio? (When i don't add the local_key on the configuration.yaml file then HASSio gives me error)

![proscenic login 2](https://user-images.githubusercontent.com/63125991/79591133-612f4300-80d8-11ea-9523-6a6a89fcdae3.PNG)
![proscenic login 3](https://user-images.githubusercontent.com/63125991/79591136-61c7d980-80d8-11ea-84f4-a216333fafb8.PNG)
![proscenic login](https://user-images.githubusercontent.com/63125991/79591138-62607000-80d8-11ea-8fe1-61940bb07ed2.PNG)

**Comment by edenhaus** [comment]
you can try the AuthCode form the first screenshot, but it looks like, that prosenic changed the communication framework. On the 820T you can see  request to the "tuyacloud" and in your screenshot it will try to connect to "robotbona".

It is required to enter a local_key as this key is used to encrypt the messages to the robot.

**Comment by terslowe** [comment]
No luck with authcode. I get this error on HASSio

Failed config
  vacuum.prosenic: 
    - Invalid config for [vacuum.prosenic]: expected str for dictionary value @ data['local_key']. Got "xxxxxxx". (See ?, line ?). 
    - platform: prosenic
      device_id: xxxxxxxxxx
      host: xxxxxxxxx
      local_key: xxxxxxxxx
      remember_fan_speed: False

I am using the app from IOS "Proscenic Robotic" There is also an another app Proscenic but not tried that.

**Comment by edenhaus** [comment]
I use the App ProsenicHome. Please try this one.

Sorry but your config will not help as you replaced everything with x for privacy reason.

**Comment by terslowe** [comment]
Tried the Proscenic Home app on IOS but no option to add 790t to the app.

Failed config
vacuum.prosenic:
- Invalid config for [vacuum.prosenic]: expected str for dictionary value @ data['local_key']. Got "**(Auth-Code from the mitmproxy)**". (See ?, line ?).
- platform: prosenic
device_id: **(Device ID from the mitmproxy)**
host: 10.0.0.4 **(IP adres of the Proscenic Robot)**
local_key: **(Auth-Code from the mitmproxy)**
remember_fan_speed: False

**Comment by edenhaus** [comment]
Then I probably have to say, that Prosenic has changed the communication library somewhere between 790 and 820. I think probably with 800.
This means that in this case this integration will not work for you at least in the current version.
I don't have a 790 and therefore I can't give it a closer look. Sorry

In the home assistant forum there is a post about the 790, but I don't know how and if the code will work.
