### ISSUE TITLE
Local Key identification - help needed

### ISSUE THREAD

**Issue by jpsmith16** [edenhaus/ha-prosenic#4]
Hi

My issue is similar to Closed Issue No. 2 "Can't find Local_Key" I have been able to set up my Proscenic vacuum (Model is 850T) in the Tuya Smart app and have been able to use tuya cli-wizard to get device id and local_key. This has enabled me to use this plug-in to get the vacuum into Home Assistant

However, I would like to be able to use the ProscenicHome app as it give me data on the vacuum about consumable parts status. I am using iOS device with mitmproxy to try and get the local key, but for the life of me I can't find it! Have checked through multiple screens, logged out of Proscenic Home app, logged back in, refreshed devices, removed & re-added devices & tried multiple strings that I think might be the local_key, but the vacuum will not appear in Home Assistant. Below is an example of what I see from Mitmproxy after I refresh devices. While "devices" field in code below is called out as "null", the "sn" field matches the device_id provided by the tuya-cli wizard and works for Home Assistant when I have the vacuum set up in the Tuya Smart app

Any help on this would be much appreciated!

{
    "code": 0,
    "data": {
        "content": [
            {
                "cloud": 1,
                "code": "850TP_1",
                "ctrlversion": null,
                "deviceId": null,
                "enabled": true,
                "faqUrl": null,
                "homeId": null,
                "imgUrl": "http://mobile.proscenic.cn/images/850T.png",
                "jump": "850TP_1",
                "model": "800_Common",
                "name": "850T/850P(2.4G)",
                "scMac": null,
                "scSV": null,
                "shared": false,
                "sn": "XXXXXXXXXXXXXXXXXXXX",
                "status": true,
                "type": "CleanRobot",
                "typeName": "CleanRobot"
            }
        ],
        "empty": false,
        "first": true,
        "last": true,
        "number": 0,
        "numberOfElements": 1,
        "pageable": {
            "offset": 0,
            "pageNumber": 0,
            "pageSize": 10,
            "paged": true,
            "sort": {
                "empty": true,
                "sorted": false,
                "unsorted": true
            },
            "unpaged": false
        },
        "size": 10,
        "sort": {
            "empty": true,
            "sorted": false,
            "unsorted": true
        },
        "totalElements": 1,
        "totalPages": 1
    },
    "msg": "OK"
}

**Comment by jpsmith16** [comment]
Also, I meant to add that every time I add the vacuum back into the Tuya Smart app, the local key changes, so the local key previously in my configuration.yaml file doesn't work

**Comment by edenhaus** [comment]
Hi,
as written in the Readme I don't have anymore a prosenic robot and therefore I don't can help you. As I can remeber me the local key was not in the first request. The only tipp I can give you is, that you check every request again.

You don't need to remove the vacuum from your profile and yes, if you start a new pairing process the key will be replaced.
Try to logout from the app and login again. Maybe only during the login process the local key will be requested.

Sorry but without the prosenic robot it's really hard to help you. Maybe they changed something on their servers.

**Comment by jpsmith16** [comment]
Hi

Thanks for getting back to me and no problem at all...I'll keep trying!
