### ISSUE TITLE
Probleme block boundary in ECB

### ISSUE THREAD

**Issue by solide184** [edenhaus/ha-prosenic#5]
Bonjour

Installation ok
device_id, ip address and local key of your prosenic vacuum cleaner ok

I have a big problem with the program.
The log gives me the following error:

Logger: custom_components.prosenic.vacuum
Source: custom_components/prosenic/vacuum.py:295
Integration: prosenic (documentation)
First occurred: 19:45:40 (4 occurrences)
Last logged: 19:46:40
Got exception while fetching the state: Data must be aligned to block boundary in ECB mode 

unable to operate robot

How can I solve my problem??

**Comment by solide184** [comment]
J'ai un cocosmart 800T

**Comment by Fred-Lo** [comment]
je suis dans le meme cas

**Comment by Fred-Lo** [comment]
avec un cocosmart 820T

**Comment by solide184** [comment]
En attendant la réponse du développeur. Tu peux utiliser l'application tuya pour appairé le robot. 
Tu peux ainsi utiliser le robot sur HA avec une scène. 

Procédure. 
- clique sur +  avec l'appli tuya
- colonne gauche choisir petit appareils
- Aspirateur robot wifi
- Rentre tes identifiants wifi box
-  sur le robot appui sur le bouton recharge pendant 6s. tu va entendre 2 sonnerie. relâche.
- retour appli tuya clique sur  vérifier que le témoin clignote rapidement.  Suivant.
- Logiquement il va apparaitre dans tes appareils Appli Tuya.

Création scenario manuel

- Exécuter scenario manuel
- tache cocosmart  mode smart , delai 10s, cocosmart strong
- nom : Robot On
- sauvegarder

Création scenario manuel

- Executer scenario manuel
- tache cocosmart  mode chargego
- nom : Robot recharge
- sauvegarder

Sur HOMEASSITANT
- config
 - intégration
 - cherche tuya 
 - rentre tes identifiants.

Logiquement tu pourra lancer les 2 scènes sur HA.

**Comment by edenhaus** [comment]
Can you please write in english. I don't understand your language

**Comment by Fred-Lo** [comment]
Sorry I'm French

**Comment by Fred-Lo** [comment]
Sorry for the translation I use the Google translator here is the problem I can not integrate my cocosmart 820T with your integration I have recovered the ip address the local key and the device id on iot tuya but after restarting the server I am unable to use my vacuum cleaner in the log I have the following error Logger: custom_components.prosenic.vacuum Source: custom_components / prosenic / vacuum.py: 295 Integration: prosenic (documentation) First occurred: 18:44:07 (824 occurrences) Last logged: 23:18:29 Got exception while fetching the state: Expecting value: line 1 column 1 (char 0)

**Comment by edenhaus** [comment]
The communication is encrypted by the local key where AES with ECB is used.
As I don't have anymore a prosenic device I cannot debug it anymore. Please try to debug it yourself.
The module used can be found: https://github.com/clach04/python-tuya

**Comment by edenhaus** [comment]
Closing as I archive this repository.
