### ISSUE TITLE
Error after update HA

### ISSUE THREAD

**Issue by pex81** [edenhaus/ha-prosenic#6]
Hi, after update Home Assistant Core on 2021.2.1 this custom_component not work.
I have this error on check configuration.

`
Platform error vacuum.prosenic - No module named 'pytuya'
` 

it's possibile to solve?

**Comment by edenhaus** [comment]
can you please check if you can install the module manually with pip?

**Comment by pex81** [comment]
Ok thanks, I re-install manually, now re-work. I don't know why !
